# Generated by Django 3.2.25 on 2026-02-13 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('emergency_action_title', models.CharField(default='ACİL EYLEM', max_length=200)),
                ('emergency_action_steps', models.JSONField()),
                ('kitchen_pharmacy', models.JSONField()),
                ('forbidden_zone', models.JSONField()),
                ('scientific_corner_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
