# Generated by Django 3.2.25 on 2026-02-15 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='downvotes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='condition',
            name='upvotes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
