# Generated by Django 3.2.25 on 2026-02-16 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0002_auto_20260215_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('embedding', models.JSONField()),
            ],
        ),
    ]
